name: verifier-xrp

services:
  database:
    container_name: verifier-xrp-database
    image: postgres:16
    env_file:
      - database.env
    ports:
      - 127.0.0.1:25433:5432
    restart: unless-stopped
    volumes:
      - xrp-indexer-database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 60s
      start_interval: 2s

  indexer:
    container_name: verifier-xrp-indexer
    image: ghcr.io/flare-foundation/verifier-xrp-indexer:v1.0.1
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml

  verifier:
    image: ghcr.io/flare-foundation/verifier-indexer-api:v1.1.0
    container_name: verifier-xrp-verifier
    env_file:
      - verifier.env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 9503:3100


volumes:
  xrp-indexer-database:
