name: verifier-btc

x-django: &django
  image: ghcr.io/flare-foundation/verifier-utxo-indexer:v1.0.2
  env_file:
    - indexer.env
  environment:
    DB_PORT: 5432
    DB_HOST: database
  volumes:
    - btc-indexer-static:/appdata/static
    - btc-indexer-media:/appdata/media
  restart: unless-stopped
  depends_on:
    database:
      condition: service_healthy

x-django-management: &django-management
  <<: *django
  depends_on:
    database:
      condition: service_healthy
    indexer-server:
      condition: service_healthy


services:
  database:
    container_name: verifier-btc-database
    image: postgres:16
    env_file:
      - database.env
    ports:
      - 127.0.0.1:25431:5432
    restart: unless-stopped
    volumes:
      - btc-indexer-database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 60s
      start_interval: 2s

  verifier:
    image: ghcr.io/flare-foundation/verifier-indexer-api:v1.1.0
    container_name: verifier-btc-verifier
    env_file:
      - verifier.env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 9501:3100

  indexer-server:
    <<: *django
    container_name: verifier-btc-server
    ports:
      - 127.0.0.1:8401:8400
    healthcheck:
      test: ["CMD", "curl", "-s", "--fail", "-o", "/dev/null", "http://127.0.0.1:8400/metrics"]
      interval: 60s
      start_period: 60s
      start_interval: 2s

  indexer-indexer:
    <<: *django-management
    container_name: verifier-btc-index-blocks
    command: django-management block_indexing

  indexer-prune:
    <<: *django-management
    container_name: verifier-btc-prune-blocks
    command: django-management block_pruning

volumes:
  btc-indexer-static:
  btc-indexer-database:
  btc-indexer-media:
